import cantera as ct
import numpy as np
import csv
from scipy.interpolate import interp1d
import os
import json
from math import ceil




def createOneDimFields(mech_path, fuel, T, P, Phi):
    r"""create one-dimensional flame initial fields using Cantera"""
    p = P* ct.one_atm  # pressure
    #  T  unburned gas temperature [K]
    oxidizer = "O2:0.21,N2:0.79" # mole fraction
    phi= Phi
    csv_file = os.path.join(".",  f"adiabatic_flame_{fuel}_T={T}K_P={P}atm_Phi={Phi}.csv")

    width = 0.03  # m
    loglevel = 1  # amount of diagnostic output (0 to 8)

    # Solution object used to compute mixture properties, set to the state of the
    # upstream fuel-air mixture
    gas = ct.Solution(mech_path)
    #gas.TPX = T, p, reactants
    gas.TP = T, p
    gas.set_equivalence_ratio(phi, fuel, oxidizer)

    # Set up flame object
    f = ct.FreeFlame(gas, width=width)
    f.set_refine_criteria(ratio=3, slope=0.06, curve=0.12)
    #f.show_solution()

    # Solve with mixture-averaged transport model
    f.transport_model = 'Mix'#'UnityLewis'#'Mix'
    f.solve(loglevel=loglevel, auto=True,)

    print('mixture-averaged flamespeed = {0:7f} m/s'.format(f.velocity[0]))

    with open(csv_file, 'w') as outfile:
        writer = csv.writer(outfile)
        writer.writerow(['z (m)']  +  ['p (Pa)'] +  ['U (m/s)'] + ['T (K)'] + gas.species_names)
        for i in range(len(f.grid)):
            writer.writerow([f.grid[i]] + [p] + [f.velocity[i]] + [f.T[i]] + list(f.Y[:,i]))

    print(f"Cantera output written to {csv_file}")

    maxSlope = ( f.T[1] - f.T[0] ) / ( f.grid[1] - f.grid[0] )
    for i in range(2,f.flame.n_points):
        slope=( f.T[i] - f.T[i-1] ) / ( f.grid[i] - f.grid[i-1] )
        if slope > maxSlope :
            maxSlope = slope
    flameThickness=  (max(f.T)-min(f.T))/maxSlope
    outfile.close()
    print('flameThickness =', flameThickness)


def convert2FoamOneDimFileds(case_name, timefold, mech_path, fuel, T, P, Phi):
    """
    convert one-dimensional laminar flame initial fields generated by Cantera to openFOAM format. 
    """
    # read variable names from .csv file ('cantera' to 'OpenFoam')
    # phi = 1
    # timefold = 0
    #fname = ['adiabatic_flame_phi_CH4_1200K=',num2str(phi),'.csv'];
    # fname = 'adiabatic_flame_CH4_500K_phi=1.csv'
    fname = f"adiabatic_flame_{fuel}_T={T}K_P={P}atm_Phi={Phi}.csv"

    with open(fname, 'r') as file:
        vars = np.genfromtxt(file, delimiter=',', max_rows=1, dtype=str)

    # read data from Cantera .csv generated file
    with open(fname, 'r') as file:
        hdr = file.readline()
        num = hdr.count(',')
        cantera = np.genfromtxt(file, delimiter=',', skip_header=1, filling_values=0)

    N_data = len(cantera)
    N_vars = len(cantera[0]) - 1
    x_cantera = cantera[:, 0] # x-axis grids (m)
    T_cantera = cantera[:, 3] # x-axis temperature (K)
    Tu = T_cantera[0]         # unburnt gas T (K)
    Tb = T_cantera[-1]        # burnt gas T (K)
    L = x_cantera[-1]         # length of domain (m)
    Sl = cantera[0, 2]        # laminar flame speed from Cantera (f.u[0])

    # check laminar flame thickness calculation in Python with Matlab
    dx_cantera = np.diff(x_cantera)
    dT_cantera = np.diff(T_cantera)
    Lf = (Tb - Tu) / max(dT_cantera / dx_cantera)
    min_dx = Lf / 22.8668  # change here 4335
    min_cells = L / min_dx
    # min_cells = 57099
    print('Length of domain: L = %.15g m' % L)
    print('Laminar flame speed: Sl = %.15g m/s' % Sl)
    print('Laminar flame thickenss: Lf = %.15g m' % Lf)
    print('Minimum grid spacing required: dx_min = %.15g m' % min_dx)
    print('Minimum # of cells  required: %.2f cells' % min_cells)

    varname = [str(vars[i+1]) for i in range(N_vars)]
    varname[0] = 'p'
    varname[1] = 'U'
    varname[2] = 'T'

    # Interpolation
    xStart = 0
    xEnd = L

    OF_gridSize = ceil(min_cells)
    OF_grid = np.linspace(xStart, xEnd, OF_gridSize)
    

    OF_data = []
    for i in range(N_vars):
        F = interp1d(x_cantera, cantera[:, i+1], kind='linear', fill_value="extrapolate")
        data = F(OF_grid)
        for k in range(len(data)):
            if data[k] < 0:
                data[k] = 0
        OF_data.append(data)

    # Write data into OpenFOAM format, 0/ folder
    zero_field_path = os.path.join(case_name, f"{timefold}")
    os.makedirs(zero_field_path, exist_ok=True)

    cwd = os.getcwd()
    os.chdir(f"{zero_field_path}")
    # os.makedirs(f"{timefold}", exist_ok=True)
    # os.chdir(f"{timefold}")

    for i in range(N_vars):
        with open(varname[i], 'w') as file:
            file.write('/*---------------------------------------------------------------------------*\\\n')
            file.write('| =========                 |                                                 |\n')
            file.write('| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |\n')
            file.write('|  \\\\    /   O peration     | Version:  5.x                                   |\n')
            file.write('|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      |\n')
            file.write('|    \\\\/     M anipulation  |                                                 |\n')
            file.write('\\*---------------------------------------------------------------------------*/\n')
            file.write('FoamFile\n')
            file.write('{\n')
            file.write('    version     2.0;\n')
            file.write('    format      ascii;\n')
            if varname[i] == 'U':
                file.write('    class       volVectorField;\n')
            else:
                file.write('    class       volScalarField;\n')
            file.write('    location    "%s";\n' %timefold)
            file.write('    object       %s;\n' % varname[i])
            file.write('}\n')
            file.write('// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n')
            file.write('\n')

            if varname[i] == 'T':
                file.write('dimensions      [0 0 0 1 0 0 0];\n\n')
                file.write('internalField   nonuniform List<scalar>\n')
                file.write('%d\n' % OF_gridSize)
                file.write('(\n')
                np.savetxt(file, OF_data[i], newline='\n', fmt='%.15f')
                file.write(')\n;\n')
            elif varname[i] == 'U':
                file.write('dimensions      [0 1 -1 0 0 0 0];\n\n')
                file.write('internalField   nonuniform List<vector>\n')
                file.write('%d\n' % OF_gridSize)
                file.write('(\n')
                np.savetxt(file, OF_data[i], newline='\n', fmt='(%.15f 0.0 0.0)')
                # np.savetxt(file, np.column_stack((OF_data[i], np.zeros_like(OF_data[i]), np.zeros_like(OF_data[i]))), newline='\n', fmt='(%.15f 0.0 0.0)')
                file.write(')\n;\n')
            elif varname[i] == 'p':
                file.write('dimensions      [1 -1 -2 0 0 0 0];\n\n')
                file.write('internalField   nonuniform List<scalar>\n')
                
                file.write('%d\n' % OF_gridSize)
                file.write('(\n')
                np.savetxt(file, OF_data[i], newline='\n', fmt='%.15e')
                file.write(')\n;\n')
            else:
                file.write('dimensions      [0 0 0 0 0 0 0];\n\n')
                file.write('internalField   nonuniform List<scalar>\n')
                file.write('%d\n' % OF_gridSize)
                file.write('(\n')
                np.savetxt(file, OF_data[i], newline='\n', fmt='%.15e')
                file.write(')\n;\n')

            file.write('\nboundaryField\n')
            file.write('{\n')
            file.write('    inlet\n')
            file.write('    {\n')
            if varname[i] == 'T':
                file.write('        type            fixedValue;\n')
                # file.write('        value           uniform 300;\n');
                file.write('        value           uniform %.8f;\n' % Tu)
            elif varname[i] == 'U':
                file.write('        type            fixedValue;\n')
                file.write('        value           uniform ( %.8f 0.000000 0.000000 );\n' % Sl)
            elif varname[i] == 'p':
                file.write('        type            zeroGradient;\n')
            elif cantera[0, i+1] > 1e-7:
                # print("i= ", i, "cantera[i+1, 0]: ", cantera[0, i+1])
                file.write('        type            fixedValue;\n')
                file.write('        value           uniform %.8f;\n' % cantera[0, i+1])
            else:
                file.write('        type            fixedValue;\n')
                file.write('        value           uniform 0;\n')
            file.write('    }\n')

            file.write('    outlet\n')
            file.write('    {\n')
            if varname[i] == 'p':
                file.write('        type            waveTransmissive;\n')
                file.write('        gamma            1.4;\n')
            else:
                file.write('        type            zeroGradient;\n')
            file.write('    }\n')

            file.write('    wall\n')
            file.write('    {\n')
            file.write('        type            empty;\n')
            file.write('    }\n')
            file.write('}\n')
            file.write('\n')
            file.write('\n')
            file.write('// ************************************************************************* //\n')
    file.close()
    ## duplicate p to p_rgh and change the object line
    os.system("cp p p_rgh")
    os.system("sed -i '/object/s/.*/\tobject  \tp_rgh;/' p_rgh")

    ## record the initial conditions in .json file
    info = {}
    info["field_type"] = "laminar flame"
    info["mechanism"] = mech_path
    info["fuel"] = fuel
    info["grid_size"] = OF_gridSize
    info["T0"] = T
    info["P0"] = P 
    info["Phi"] = Phi
    with open("_info_.json", "w") as f:
        f.write(
             json.dumps(info,
                        ensure_ascii=False,
                        indent=4,
                        separators=(',', ':')))
    f.close()

    ## return home path
    os.chdir(cwd)

    print(f"\nopenFOAM-format fields saved in \033[32m{zero_field_path}/\033[0m")
    print(f'The number of grids:            \033[32m{OF_gridSize}\033[0m')
    print(f"The initial temperature:        \033[32m{T} K\033[0m")
    print(f"The initial pressure:           \033[32m{P} atm\033[0m")
    print(f"The initial equivalence ratio:  \033[32m{Phi}\033[0m")
    print("\033[1;32mCONVERTION FINISHED\033[0m")



def cleanCSV(fuel, T, P, Phi):
    fname = f"adiabatic_flame_{fuel}_T={T}K_P={P}atm_Phi={Phi}.csv"
    if os.path.exists(fname):
        os.remove(fname)
        print(f"Clear CSV: {fname}")




def convert2FoamZeroDimFields(case_name, timefold, mech_path, fuel, T, P, Phi, reactor="constant_pressure"):
    """
    """

    gas = ct.Solution(mech_path)
    gas.TP = T, P* ct.one_atm
    oxidizer = "O2:0.21, N2:0.79" # mole fraction
    
    gas.set_equivalence_ratio(Phi, fuel, oxidizer)

    fuel_inex = gas.species_names.index(fuel)
    N2_index = gas.species_names.index("N2")
    O2_index = gas.species_names.index("O2")

    key_map = {
              fuel: "$Yfuel",
              "O2": "$Yo2",
              "N2": "$Yn2",
              "Ydefault": "0.0",
              "T":  "$T0",
              "p":  "$p0",
              "p_rgh": "$p0",
              "U": "(0 0 0)"
              }

    with open("settings", 'w') as file:
        file.write(f"// generator: ct2foam\n")
        file.write(f"// mechanism: {mech_path}\n")
        file.write(f"// zero-dimensional reaction initial conditions: T0={T} K, P0={P} atm, Phi={Phi}\n")
        file.write(f"// reactor type: {reactor}\n\n")
        file.write(f"T0      {T};\n")
        file.write(f"p0      {P*ct.one_atm};\n")
        file.write(f"Yfuel   {gas.Y[fuel_inex]};\n")
        file.write(f"Yn2     {gas.Y[N2_index]};\n")
        file.write(f"Yo2     {gas.Y[O2_index]};\n")
    
    # Write data into OpenFOAM format, 0/ folder
    zero_field_path = os.path.join(case_name, f"{timefold}")
    os.makedirs(zero_field_path, exist_ok=True)

    cwd = os.getcwd()
    os.chdir(f"{zero_field_path}")


    variables = ["T", "p", "p_rgh", fuel, "N2", "O2", "Ydefault", "U"]


    for i, variable in enumerate(variables):
        with open(variable, 'w') as file:
            ## file header info
            file.write('/*---------------------------------------------------------------------------*\\\n')
            file.write('| =========                 |                                                 |\n')
            file.write('| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |\n')
            file.write('|  \\\\    /   O peration     | Version:  5.x                                   |\n')
            file.write('|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      |\n')
            file.write('|    \\\\/     M anipulation  |                                                 |\n')
            file.write('\\*---------------------------------------------------------------------------*/\n')
            file.write('FoamFile\n')
            file.write('{\n')
            file.write('    version     2.0;\n')
            file.write('    format      ascii;\n')
            if variable == "U":
                file.write('    class       volVectorField;\n')
            else:
                file.write('    class       volScalarField;\n')
            file.write('    location    "%s";\n' %timefold)
            file.write('    object       %s;\n' % variable)
            file.write('}\n')
            file.write('// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n')
            file.write('\n')

            ## value set
            if variable == "Ydefault":
                file.write('dimensions      [0 0 0 0 0 0 0];\n\n')
                file.write('internalField   uniform %s;\n\n' % key_map[variable])
            elif variable=="U" :
                file.write('dimensions      [0 1 -1 0 0 0 0];\n\n')
                file.write('internalField   uniform %s;\n\n' % key_map[variable])
            else:
                if variable == "T":
                    file.write('dimensions      [0 0 0 1 0 0 0];\n\n')
                elif variable == "p" or variable == "p_rgh":
                    file.write('dimensions      [1 -1 -2 0 0 0 0];\n\n')
                elif variable=="U" :
                    file.write('dimensions      [0 1 -1 0 0 0 0];\n\n')
                else:
                    file.write('dimensions      [0 0 0 0 0 0 0];\n\n')
                
                file.write('#include "../settings"\n\n')
                file.write('internalField   uniform %s;\n\n' % key_map[variable])


            ## boundary condition

            file.write('boundaryField\n')
            file.write('{\n')
            file.write('    WALL\n')
            file.write('    {\n')
            
            ## constant P or constant V
            if variable in ["p", "p_rgh"] and reactor == "constant_pressure":
                file.write('        type            fixedValue;\n')
                file.write('        value           $internalField;\n')
            elif variable == "U":
                file.write('        type            fixedValue;\n')
                file.write('        value           uniform (0 0 0);\n')
            else:
                file.write('        type            zeroGradient;\n')
            file.write('    }\n\n')

            file.write('    EMPTY\n')
            file.write('    {\n')
            file.write('        type            empty;\n')
            file.write('    }\n')
            file.write('\n}\n\n\n')
            file.write('// ************************************************************************* //\n')
        file.close()

    ## record initial conditions in .json file
    ## record the initial conditions in .json file
    info = {}
    info["field_type"] = "zero-dimensional"
    info["reactor_type"] = reactor
    info["mechanism"] = mech_path
    info["fuel"] = fuel
    info["T0"] = T
    info["P0"] = P 
    info["Phi"] = Phi
    with open("_info_.json", "w") as f:
        f.write(
             json.dumps(info,
                        ensure_ascii=False,
                        indent=4,
                        separators=(',', ':')))
    f.close()

    ## return home path
    os.chdir(cwd)

    print(f"\nopenFOAM-format fields saved in \033[32m{zero_field_path}/\033[0m") 
    print(f"settings saved in               \033[32m./settings\033[0m")    
    print(f"The initial temperature:        \033[32m{T} K\033[0m")
    print(f"The initial pressure:           \033[32m{P} atm\033[0m")
    print(f"The initial equivalence ratio:  \033[32m{Phi}\033[0m")
    print("\033[1;32mCONVERTION FINISHED\033[0m")

